### ISSUE TITLE
should always be synchronous

### ISSUE THREAD

**Issue by xingrz** [hzsweers/RxPalette#3]
`Palette.generateAsync` internally uses `AsyncTask`, which is not a RxJava way.

People want to generate palette asynchronously should use:

``` java
RxPalette.generate( ... )
    .subscribeOn(Schedulers.computation())
    .observeOn(AndroidSchedulers.mainThread())
```

**Comment by ZacSweers** [comment]
They probably should, but it's simple enough to support both. Its internal usage of an AsyncTask doesn't make this API any less "Rxjava way", it just defers to whatever asynchronous implementation Google chooses under the hood.

**Comment by xingrz** [comment]
Please don't. Its use of AsyncTask or any other asynchronous algorithms may forks unnecessary extra threads.

Please refer: https://github.com/square/retrofit/pull/1117

**Comment by ZacSweers** [comment]
You don't have to use `generateAsync`, and anyone else that uses it should be knowledgeable of what they're doing. If they're not and start spinning off tons of other threads, that's not my problem. To suggest blocking it is like suggesting that any library with code that could possibly be done asynchronously should only support a synchronous API. For a library this small, I'm not interested in predicting how developers are going to use the code nor am I interested in trying to coerce them into a certain asynchronous paradigm when it comes at no extra cost to support both.

Retrofit is not really comparable here. It's an extensive library and having a concise and opinionated API is important to maintain a clear interface. This library has 4 functions, it is really not a big enough deal to matter.

**Comment by ZacSweers** [comment]
I opted to actually go with this approach anyway, namely because asynchronous unit testing was proving annoying and it was going to be tedious maintaining 4 different `OnSubscribe` implementations
